import { Accordion, Extensions, Features, Footer, Header, NavBar } from 'components';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
	return (
		<main>
			<Head>
				<title>BookMark Landing Page</title>
				<meta name='description' content='Generated by MARKOS BAHGAT' />
				<link rel='icon' href='/favicon-32x32.png' />
			</Head>

			<div>
				<NavBar />
				<Header />
				<Features />
				<Extensions />
				<Accordion />
				<Footer/>
			</div>
		</main>
	);
};

export default Home;
